README.md
=> Document how to remove HTML results from API docs

docs/quickstart.md, pyproject.toml, uv.lock
@pydanny  : Add uvicorn run instructions to quick start guide to make quickstart guide give a full running application
=> Add run instructions to quickstart docs

src/air/applications.py
=> Remove the ability to change the Air default response class

src/air/templates.py, tests/test_templates.py
=> Add kwargs to Jinja2Renderer

docs/quickstart.md, pyproject.toml, src/air/__init__.py, src/air/applications.py, src/air/forms.py, tests/test_forms.py, uv.lock
For #20 
Here's the API as a test case:
```python
from typing import Annotated
from fastapi import Depends, Request
from pydantic import BaseModel
import air
app = air.Air()
class CheeseModel(BaseModel):
name: str
age: int
class CheeseForm(air.AirForm):
model = CheeseModel
@app.page
async def cheese():
return air.Html(
air.H1("Cheese Form"),
air.Form(
air.Input(name="name"),
air.Input(name="age", type="number"),
air.Button("Submit", type="submit"),
method="post",
action="/cheese-info",
),
)
@app.post("/cheese-info")
async def cheese_info(request: Request):
cheese = await CheeseForm.validate(request)
if cheese.is_valid:
return air.Html(air.H1(cheese.data.name))
return air.Html(air.H1(f"Errors {len(cheese.errors)}"))
```
=> Implementing form validation for Air projects

src/air/tags.py, tests/test_tags.py
=> Allow non-escaped code through Style and Script tags

README.md, pyproject.toml
Revised the project description to emphasize that the framework is built with FastAPI, Starlette, and Pydantic, providing a clearer overview of its features and technology stack.
=> Update project description in README and pyproject.toml

CONTRIBUTING.md
Expanded the contributing guide to include sections on building documentation with MkDocs, running tests, linting and formatting, and troubleshooting common issues. Also clarified the approach to plugins versus core features.
=> Update CONTRIBUTING.md with docs, tests, and troubleshooting

docs/api/background.md, mkdocs.yml, src/air/__init__.py, src/air/background.py
=> Implement FastAPI background tasks

src/air/__init__.py, src/air/responses.py
Addresses these tickets:
- #129 
- #132
- #133 
- #134 
- #135 
- #136 
- #137
=> Passthru all the responses

docs/concepts/jinja.md, main.py, mkdocs.yml, src/air/templates.py, tests/templates/jinja_airtags.html, tests/test_templates.py
=> Explaining how to use Jinja with Air Tags

.github/workflows/python-package.yml, Makefile, pyproject.toml, src/air/applications.py, src/air/forms.py, uv.lock
Speeds up type checking in non-cached environment 10x, where on around 1000 LOC it took 30 seconds now it takes 3 seconds.
=> Switch from mypy to ty

src/air/tags.py
=> Document Tag args to button

src/air/tags.py
Let's not make the project legacy quite yet.
=> Undo Optional[str]

tests/test_tags.py
=> Improve test coverage for tags.py

src/air/tags.py
=> Document more tags

CONTRIBUTING.md, pyproject.toml, src/air/__init__.py, uv.lock
=> Single source of version

src/air/tags.py
=> Document tags starting with I

src/air/tags.py, tst.html
=> Document the L tags

docs/quickstart.md
=> Add in chart example

docs/api/tags.md, docs/api/tags/a-d.md, docs/api/tags/e-m.md, docs/api/tags/index.md, docs/api/tags/n-s.md, docs/api/tags/t-z.md, docs/concepts/air_tags.md, mkdocs.yml, pyproject.toml, src/air/tags.py, uv.lock
- Adds mkdocs-ref dependency
- Splits tag docs into multiple files
=> Refactor tag docs

README.md, docs/concepts/jinja.md, docs/index.md, docs/quickstart.md, src/air/__init__.py, src/air/templates.py, tests/test_templates.py
=> Rename Jinja2Renderer to JinjaRenderer

docs/concepts/air_tags.md, docs/quickstart.md, src/air/tags.py, tests/test_tags.py
=> Tags and Tag passes through other tags when called directly

README.md
This pull request updates the `README.md` file to clarify the project's contribution guidelines and vision. The changes emphasize the goal of maintaining a minimalist core package while encouraging contributors to create extensions or packages in the broader Air ecosystem.
* Revised the contribution guidelines to reflect the project's focus on removing features from the core and promoting the creation of external packages. The updated text highlights the vision of the Air ecosystem as an integral part of the project. (`README.md`, [README.mdL27-R27](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L27-R27))
=> Clarify about minimalist core

docs/concepts/forms.md
=> Document how to use forms Starlette style

src/air/__init__.py, src/air/templates.py, tests/test_templates.py
Get it out before it confuses users. 😛
=> Remove deprecated Jinja2Renderer

.gitignore, pyproject.toml, src/air/responses.py, uv.lock
PR for #248
pyproject.toml to expose a new optional-extras group called standard.
=> pyproject.toml to expose a new optional-extras group called standard.

docs/api/index.md, src/air/templates.py
=> Add missin env and context processors to JinjaRenderer

src/air/applications.py, tests/test_applications.py
=> Convert underscores to dashes in app.page method

src/air/forms.py, src/air/tags/models/base.py, tests/test_tags.py
=> Fixes #326

src/air/forms.py, tests/test_forms.py
=> BUG: Add missing autofocus option to AirField

examples/mvpcss_hxboost.py, src/air/applications.py, src/air/dependencies.py, src/air/layouts.py, tests/test_applications.py, tests/test_layouts.py, tests/test_requests.py
=> Implement hx boost in layout functions

pyproject.toml, src/air/__init__.py, src/air/forms.py, src/air/layouts.py, src/air/requests.py, src/air/responses.py, uv.lock
Addresses the easy ones from https://github.com/feldroy/air/issues/340
Skipped the noqa for `class I` because it could affect air tag docs
=> cleanup some noqa, missing-attribute from tools.pyrefly.errors

tests/test_routing.py, tests/test_stock_tags_coverage.py, tests/test_tags_utils.py
Dropped to 89% and our threshold is 95%
=> Get test coverage back up to 95+%

docs/learn/index.md
2 broken links on https://feldroy.github.io/air/learn/
=> Fix broken links

docs/api/ext/index.md, docs/why.md, src/air/ext/sql.py
- Adds missing reference to SQL page
- Adds `lifespan` example to SQL page
- Fixes a glitch on the why page
=> SQL doc cleanup and fix why page

.github/codecov.yml, pyproject.toml
This pull request updates the project's code coverage configuration to improve reporting and coverage enforcement. The main changes include making overall coverage status informational, tightening patch coverage enforcement, and adding a comprehensive set of line exclusion patterns for coverage reports.
**Coverage reporting and enforcement:**
* Updated `.github/codecov.yml` to make overall project coverage informational only, so it will be displayed but never cause a failure. Patch coverage checks are now stricter, allowing only a 1% drop (was 0.5%), and will still fail if the threshold is exceeded.
**Coverage report accuracy:**
* Added a detailed set of exclusion patterns to the `exclude_lines` section in `pyproject.toml` to filter out non-executable code, imports, type hints, …
=> chore: update Codecov config and refine coverage exclusions

CONTRIBUTING.md
#462 
Cleanup of text and removal of tangential reference information.
=> Make contributing.md more concise

docs/api/ext/sql.md, docs/learn/air_tags.md, docs/learn/cookbook/index.md, docs/learn/index.md, docs/learn/quickstart.md, docs/learn/sql.md, docs/learn/tutorial.md
Various corrections:
- Replace unrecognised relative link with recognised relative links
- Cleanup intro to SQL docs to list database-specific dependencies
- Bolded links in the learn section
=> Various minor fixes to documentation

MAINTAINERS.md
How we do releases, put in a file for maintainers.
=> Bring forward old version release instructions

docs/about/alternatives.md, mkdocs.yml
Use admonitions instead of block quotes, as this looks better and doesn't mess with side navigation
OLD: 
NEW:
=> Move alternatives to use admonitions

examples/airblog.py, examples/airblog/hello-world.md, examples/airblog/markdown-features.md
Adds a simple markdown-powered blog example to show how to build simple projects. It is designed to run as a stand-alone script.
> [!NOTE]  
> As this is intended to be run as an independant script it won't pass all of Air's normal linting checks. That's why it contains a number of `X: ignore` directives near the top of the code.
=> Add airblog example

docs/tools.md
Refers to "AirBread", an AI-powered search on Air Docs so people can ask questions rather than just use terms via full-text search. Nothing wrong with full-text search, but this may be more beginner friendly.
=> Add mixed bread AI search on docs

docs/learn/cookbook/bigger-applications.md
#510 
Change to focus on AirRouter rather than app mounting, as the former provides a lot more controls.
=> Show use of include router for bigger apps

docs/api/requests.md
https://github.com/feldroy/air/issues/453
Added a dedicated documentation content for `air.requests.Request`
=> docs(requests): add usage and recipes for requests.Request
