feldroy/air

.github/workflows/tests.yml
Create a GitHub Actions workflow for running tests with `rye run tox`.
* **GitHub Actions Workflow**
- Add a new workflow file `.github/workflows/tests.yml`.
- Set the workflow to run on push and pull request events for the `main` branch.
- Use an `ubuntu-latest` environment.
- Set up a Python 3.12 environment.
- Install dependencies using `rye sync`.
- Run tests using `rye run tox`.
---
For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/feldroy/air?shareId=1d44d969-d2a0-4cbb-b02b-613253e7d204).
=> Create a GitHub Actions workflow for running tests with Tox

README.md
I noticed that this link pointed to https://github.com/feldroy/air/blob/main/@audreyfeldroy, which led to a 404
=> docs: fix link to audrey.feldroy.com in README

CONTRIBUTING.md, README.md
* Explicitly tell users to create a uv virtualenv, to minimize risk of dependency conflicts
* Encourage contributor setup
* Have future contributors fork the repo
=> Improve install docs

README.md, src/air/__init__.py, src/air/templates.py, tests/templates/home.html, tests/test_templates.py
1. Introduces `templates.Jinja2Renderer`, wraps FastAPI/Starlette Jinja2 generator
2. Adds tests to support new class
3. API is designed to shorten characters typed to return a Jinja2-powered response
For #21
=> Shortcut renderer for jinja2

README.md, docs/index.md, docs/quickstart.md, pyproject.toml, src/air/__init__.py, src/air/applications.py, tests/conftest.py, tests/test_applications.py, tests/test_templates.py, uv.lock
This adds an `applications.Air` wrapper for `fastapi.FastAPI`. With this, the default view response is a `TagResponse`, so a minimal app looks like this:
```python
import air
app = air.Air()
@app.get('/')
async def index():
return air.H1('Hello, world')
```
=> Create applications.Air wrapper for fastapi.FastAPI

docs/air-tags.md, src/air/tags.py, tests/test_tags.py
This fixes #57 and #44.
#44 was caused by a `int` type being passed in where only Tags and str had been planned. Need to figure out other types too.
=> Convert Tag.children to for loop and fix bug

src/air/__init__.py, src/air/tags.py, tests/test_responses.py, tests/test_tags.py
- Reduces the scope of the Html tag and removes the Htmx tag
- Doesn't address that injecting tags is a default behavior of tags, let's handle that in #69 69
=> Remove headers arg from Html tag

.gitignore, .vscode/settings.json, docs.md, docs/concepts/forms.md, main.py, mkdocs.yml, src/air/forms.py, src/air/tags.py, tests/test_forms.py, tst.html
=> Form rendering

src/air/tags.py
If the type isn't supported, we just convert to `str` and then escape it for safety. This matches to what most template tools (jinja, django, mako, FT components, etc) do, which prevents hard bugs in production (aka 500 errors) from stopping users cold.
=> Stringify/escape unsupported tag children so 500 errors aren't thrown on tag children type failures

src/air/__init__.py
- Grouped all 100+ individual 'from .tags import' statements into a single multi-line import
- Reduced file size from 359 to 133 lines, improving readability
- Maintained alphabetical ordering of imports for easier navigation
- Preserved explicit re-export pattern with 'as' aliases to keep public API clear
- Included previously separated imports (Children, Tag) in the consolidated group
This change makes the module initialization cleaner and easier to maintain without affecting the public API or functionality.
=> refactor: consolidate tag imports in __init__.py

src/air/responses.py, src/air/tags.py, tests/test_responses.py, tests/test_tags.py
For #253 
This pull request refactors how Server-Sent Events (SSE) responses are generated and handled in the `air` framework, particularly focusing on the `SSEResponse` class. The main improvements include centralizing and simplifying the logic for formatting SSE messages, enhancing support for both tag and string content, and updating tests to use the `air.Air` app class instead of `FastAPI`. The changes also add more robust test coverage for multiline content in SSE responses.
**SSEResponse and SSE message formatting:**
* Refactored the SSE message formatting logic from the `Tag.encode()` method into the new `SSEResponse.stream_response()` method, allowing both `Tag` instances and plain strings to be streamed as SSE messages, including support for multiline content. …
=> BUG: SSEResponse now Handles str and Tag types, with linebreaks handled cleanly

justfile, pyproject.toml
- Consolidated redundant Ruff commands in `justfile` for simplification.
- Reorganized `pyproject.toml` to enhance readability, moving the `dependencies` block and adding `project.urls`.
- Included `license` metadata in `pyproject.toml` for improved clarity.
=> Feat pyproject.toml - Part 1

.env, pyproject.toml
For #274, this replaces the proof-of-concept and mostly unmaintained pytest-rich with its maintained successor, pytest-modern. While arguably not as pretty, it does produce correct results on assert. Also works great with pdbpp.
=> Switch from pytest-rich to pytest-modern

.github/workflows/python-package.yml, .github/workflows/release-to-pypi.yml, README.md, pyproject.toml, tests/test_applications.py, uv.lock
- Refined CI workflows, including better OS support, enhanced concurrency settings, and updated naming for clarity.
- Introduced annotations for failed tests using `pytest-github-actions-annotate-failures`.
- Removed outdated or redundant dependencies such as `pytest-rich` and replaced with `pytest-pretty`.
- Enhanced coverage settings by adding `ignore_errors` in `pyproject.toml` and integrating `pytest-cov` for clearer insights.
- Updated `justfile` commands for better consistency and added `test-coverage` and `test-durations` for improved testing metrics.
- Addressed test-related issues by removing incorrect assertions and improving verbosity for debug purposes.
=> Improve CI workflows, annotations in the GitHub using GitHub Actions and CI for ubuntu-latest, windows-latest, macos-latest 

src/air/forms.py, tests/test_forms.py, uv.lock
Enhanced the AirForm class to return a boolean from the validate method and updated its docstring with usage examples. Added unit tests for AirForm validation logic to ensure correct behavior.
=> FEAT: AirForm.validate method returns boolean instead of None

src/air/layouts.py, tests/test_applications.py, tests/test_layouts.py
Fixes https://github.com/feldroy/air/issues/333
By default, [mvpcss](https://unpkg.com/mvp.css@1.17.2/mvp.css) applies the following padding to the `header`, `main`, and `footer` blocks:
```css
footer,
header,
main {
margin: 0 auto;
max-width: var(--width-content);
padding: 3rem 1rem;
}
```
I’ve overridden the padding and reduced it to `1rem`.
=> Override mvpcss default layout padding

src/air/forms.py, tests/test_forms.py
For #372 introduces an 'includes' attribute to AirForm, allowing selective rendering of model fields in forms. Updates default_form_widget and render logic to respect the 'includes' sequence. Adds tests to verify correct behavior when 'includes' is set.
=> Add includes argument to AirForm rendering

examples/tags_render.py
- Updated the example usage command to `just run-py-module examples.tags_render`.
Fixes #436
=> Updated the example usage command to `just run-py-module examples.tags_render`.

.gitignore, docs/api/ext/auth.md, docs/api/ext/index.md, examples/github_oauth_demo.py, mkdocs.yml, pyproject.toml, src/air/ext/__init__.py, src/air/ext/auth.py, tests/ext/test_auth.py, uv.lock
This makes it possible to have easy configuration for AIR anyway that you want. Just provide three things:
- GitHub client id
- Github client secret
- A processing function for when the callback is triggered
Tasks:
Supersedes #417
=> Add GitHub OAuth router Factory

.github/workflows/latest-changes.yml, CHANGELOG.md
- Add .github/workflows/latest-changes.yml to automatically update CHANGELOG.md
- Add 'Latest Changes' section to CHANGELOG.md for new PR entries
=> Add latest-changes GitHub Action workflow (Issue #163)

CONTRIBUTING.md, README.md, justfile, pyproject.toml, uv.lock
This pull request updates the documentation and configuration to clarify and simplify the installation of optional features ("extras") for the project. It standardizes commands for installing all extras and introduces clearer instructions for contributors and users.
- Simplified commands for syncing dependencies in `CONTRIBUTING.md` and `justfile`.
- Expanded the `README.md` with detailed descriptions of optional features and installation commands.
- Added a new "all" group for combined optional dependencies in `pyproject.toml` and `uv.lock`.
- Updated versions for `authlib`, `debugpy`, `docutils`, and `fastapi`.
**Documentation improvements:**
* Updated the `README.md` to provide explicit instructions for installing each optional feature (extra), including a tip on combining extras in a …
=> Added a new "all" group for combined optional dependencies in `pyproject.toml`

docs/api/ext/sql.md, docs/learn/sql.md, src/air/ext/sql.py, tests/ext/test_sql.py
#472 
Adds `async_db_lifespan` to the `air.ext.sql` module. This means we get to stop copy/pasting lifespan functions from one project to another.
=> Add lifespan db func to air.ext.sql

src/air/responses.py, tests/ext/test_auth.py, tests/test_responses.py
Close #356 
makes the Air default for ResponseRedirect be 303, which turns it into a GET
=> FEAT: Make the default status_code of air.RedirectResponse be 303

src/air/tags/models/stock.py
https://github.com/feldroy/air/issues/172
Adding some docstrings for `stock.py`'s Tags (starts with letters P to R)
=> docs: add docstrings for P, Q and R tags

justfile, pyproject.toml, uv.lock
This pull request makes improvements to the linting workflow by enforcing a minimum version requirement for Ruff and updating how formatting checks are performed. These changes help ensure consistency and reliability in code formatting and linting.
- Enforced `ruff` version requirement in `pyproject.toml` for runtime validation (>=0.13.3).
- Adjusted `ruff` commands in `justfile` to use `--check` with customizable output format.
**Linting and formatting improvements:**
* Enforced a minimum required version of Ruff (`>=0.13.3`) in `pyproject.toml` to ensure that all contributors use a compatible version of the linter.
* Updated the `justfile` lint command to use `ruff format --check` instead of `ruff format --diff`, and set the output format dynamically, improving the accuracy and …
=> Refine `ruff` configuration
